/*
    Each new term in the Fibonacci sequence is generated by 
    adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not 
    exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main()
{
    long first_number = 1;
    long second_number = 1;
    long third_number = 0;
    long sum = 0;

    for (int i = 0; i < 4000000; i++)
    {
        if(i % 2 == 0)
        {
            sum += i;
        }

        third_number = first_number + second_number;
        first_number = second_number;
        second_number = third_number;
    }

    printf("%ld", sum);
}